namespace ServerManagementSystem.Models.ComputerHardwareClasses
{
    public class Printer
    {
        public string Attributes { get; set; }
        public string Availability {get; set;}
        public string AvailableJobSheets {get; set;}
        public string AveragePagesPerMinute {get; set;}
        public string Capabilities {get; set;}
        public string CapabilityDescriptions {get; set;}
        public string Caption {get; set;}
        public string CharSetsSupported {get; set;}
        public string Comment {get; set;}
        public string ConfigManagerErrorCode {get; set;}
        public string ConfigManagerUserConfig {get; set;}
        public string CreationClassName {get; set;}
        public string CurrentCapabilities {get; set;}
        public string CurrentCharSet {get; set;}
        public string CurrentLanguage {get; set;}
        public string CurrentMimeType {get; set;}
        public string CurrentNaturalLanguage {get; set;}
        public string CurrentPaperType {get; set;}
        public string Default {get; set;}
        public string DefaultCapabilities {get; set;}
        public string DefaultCopies {get; set;}
        public string DefaultLanguage {get; set;}
        public string DefaultMimeType {get; set;}
        public string DefaultNumberUp {get; set;}
        public string DefaultPaperType {get; set;}
        public string DefaultPriority {get; set;}
        public string Description {get; set;}
        public string DetectedErrorState {get; set;}
        public string DeviceID {get; set;}
        public string Direct {get; set;}
        public string DoCompleteFirst {get; set;}
        public string DriverName {get; set;}
        public string EnableBIDI {get; set;}
        public string EnableDevQueryPrint {get; set;}
        public string ErrorCleared {get; set;}
        public string ErrorDescription {get; set;}
        public string ErrorInformation {get; set;}
        public string ExtendedDetectedErrorState {get; set;}
        public string ExtendedPrinterStatus {get; set;}
        public string Hidden {get; set;}
        public string HorizontalResolution {get; set;}
        public string InstallDate {get; set;}
        public string JobCountSinceLastReset {get; set;}
        public string KeepPrintedJobs {get; set;}
        public string LanguagesSupported {get; set;}
        public string LastErrorCode {get; set;}
        public string Local {get; set;}
        public string Location {get; set;}
        public string MarkingTechnology {get; set;}
        public string MaxCopies {get; set;}
        public string MaxNumberUp {get; set;}
        public string MaxSizeSupported {get; set;}
        public string MimeTypesSupported {get; set;}
        public string Name {get; set;}
        public string NaturalLanguagesSupported {get; set;}
        public string Network {get; set;}
        public string PaperSizesSupported {get; set;}
        public string PaperTypesAvailable {get; set;}
        public string Parameters {get; set;}
        public string PNPDeviceID {get; set;}
        public string PortName {get; set;}
        public string PowerManagementCapabilities {get; set;}
        public string PowerManagementSupported {get; set;}
        public string PrinterPaperNames {get; set;}
        public string PrinterState {get; set;}
        public string PrinterStatus {get; set;}
        public string PrintJobDataType {get; set;}
        public string PrintProcessor {get; set;}
        public string Priority {get; set;}
        public string Published {get; set;}
        public string Queued {get; set;}
        public string RawOnly {get; set;}
        public string SeparatorFile {get; set;}
        public string ServerName {get; set;}
        public string Shared {get; set;}
        public string ShareName {get; set;}
        public string SpoolEnabled {get; set;}
        public string StartTime {get; set;}
        public string Status {get; set;}
        public string StatusInfo {get; set;}
        public string SystemCreationClassName {get; set;}
        public string SystemName {get; set;}
        public string TimeOfLastReset {get; set;}
        public string UntilTime {get; set;}
        public string VerticalResolution {get; set;}
        public string WorkOffline {get; set;}
    }
}
